### ISSUE TITLE
Plany na dalsze działanie

### ISSUE THREAD

**Issue by MateuszFerenc** [MateuszFerenc/great-tea-brewing#1]
Początek dyskusji

**Comment by Jula434** [comment]
przetrwać :')

**Comment by iNvBn** [comment]
Boże dopomóż nam.

**Comment by MateuszFerenc** [comment]
@Jula434 :
- [ ]  Nauka Tkinter dla python (potem podeślę jakieś materiały)
- [ ]  Nauka POOP (Python Object Oriented Programming)

@iNvBn :
- [x]  Gościu z konewką
- [x]  ogólnie gify i inne femboyowe (frontendowe) rzeczy

@AdasFromPL :
- [x]  Ogarnięcie wzorów
- [x]  Ogarnięcie implementacji wzorów w pythonie, propozycja funkcji

@MateuszFerenc :
- [x] Być Kozakiem
- [x]  Integracja Kodu
- [x]  Code review
- [x]  Code merge
- [x]  Agile
- [x]  Daily
- [x]  Fix event loop exit
